SinExWebApp20317887/Models/ServicePackageFee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace SinExWebApp20317887.Models
{
    [Table("ServicePackageFee")]
    public class ServicePackageFee
    {
        public virtual int ServicePackageFeeID { get; set; }
        public virtual decimal Fee { get; set; }
        public virtual decimal MinimumFee { get; set; }
        //Foreign
        public virtual int PackageTypeID { get; set; }
        public virtual int ServiceTypeID { get; set; }
        //Navigation to PackageT
        public virtual PackageType PackageType { get; set; }
        //Navigation to ServiceT
        public virtual ServiceType ServiceType { get; set; }

        //public virtual String CurrencyType { get; set; }
        //public virtual List<SelectListItem> CurrencyTypes { get; set; }
    }
}

SinExWebApp20317887/Controllers/ServicePackageFeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20317887.Models;

namespace SinExWebApp20317887.Controllers
{
    public class ServicePackageFeesController : BaseController
    {
        private SinExDatabaseContext db = new SinExDatabaseContext();

        // GET: ServicePackageFees
        public ActionResult Index(string CurrencyCode)
        {
            if (CurrencyCode == null) { CurrencyCode = "CNY"; }
            var servicePackageFees = db.ServicePackageFees.Include(s => s.PackageType).Include(s => s.ServiceType);
            foreach (var item in servicePackageFees) {
                item.Fee *= ChangeCurrency(CurrencyCode);
            }
            return View(servicePackageFees.ToList());
        }

/*        public ActionResult ChangeCurrencies(string CurrencyType) {
            string temp2 = Request["CurrencyType"];
            string temp=ViewBag.CurrencyType;
            //ViewBag.CurrentCurrency = currency;
           // var c = new ServicePackageFee();
            //c.CurrencyTypes = popularDropDownCurrency().ToList();
            //ViewBag.currency = currentCurrency;
            return View();
        }
        public SelectList popularDropDownCurrency() {
            string[] arr = new string[4];
            arr[0] = "CNY";
            arr[1] = "HKD";
            arr[2] = "TWD";
            arr[3] = "MOP";
            return new SelectList(arr);
        }*/

        // GET: ServicePackageFees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            if (servicePackageFee == null)
            {
                return HttpNotFound();
            }
            return View(servicePackageFee);
        }

        // GET: ServicePackageFees/Create
        public ActionResult Create()
        {
            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type");
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type");
            return View();
        }

        // POST: ServicePackageFees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ServicePackageFeeID,Fee,MinimumFee,PackageTypeID,ServiceTypeID")] ServicePackageFee servicePackageFee)
        {
            if (ModelState.IsValid)
            {
                db.ServicePackageFees.Add(servicePackageFee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type", servicePackageFee.PackageTypeID);
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type", servicePackageFee.ServiceTypeID);
            return View(servicePackageFee);
        }

        // GET: ServicePackageFees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            if (servicePackageFee == null)
            {
                return HttpNotFound();
            }
            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type", servicePackageFee.PackageTypeID);
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type", servicePackageFee.ServiceTypeID);
            return View(servicePackageFee);
        }

        // POST: ServicePackageFees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ServicePackageFeeID,Fee,MinimumFee,PackageTypeID,ServiceTypeID")] ServicePackageFee servicePackageFee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(servicePackageFee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PackageTypeID = new SelectList(db.PackageTypes, "PackageTypeID", "Type", servicePackageFee.PackageTypeID);
            ViewBag.ServiceTypeID = new SelectList(db.ServiceTypes, "ServiceTypeID", "Type", servicePackageFee.ServiceTypeID);
            return View(servicePackageFee);
        }

        // GET: ServicePackageFees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            if (servicePackageFee == null)
            {
                return HttpNotFound();
            }
            return View(servicePackageFee);
        }

        // POST: ServicePackageFees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ServicePackageFee servicePackageFee = db.ServicePackageFees.Find(id);
            db.ServicePackageFees.Remove(servicePackageFee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SinExWebApp20317887/Views/ServicePackageFees/Create.cshtml
@model SinExWebApp20317887.Models.ServicePackageFee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServicePackageFee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinimumFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinimumFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinimumFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PackageTypeID, "PackageTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PackageTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PackageTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceTypeID, "ServiceTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20317887/Views/ServicePackageFees/Delete.cshtml
@model SinExWebApp20317887.Models.ServicePackageFee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ServicePackageFee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PackageType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PackageType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinimumFee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinimumFee)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SinExWebApp20317887/Views/ServicePackageFees/Details.cshtml
@model SinExWebApp20317887.Models.ServicePackageFee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ServicePackageFee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PackageType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PackageType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinimumFee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinimumFee)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ServicePackageFeeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SinExWebApp20317887/Views/ServicePackageFees/Edit.cshtml
@model SinExWebApp20317887.Models.ServicePackageFee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ServicePackageFee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ServicePackageFeeID)

        <div class="form-group">
            @Html.LabelFor(model => model.Fee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MinimumFee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinimumFee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinimumFee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PackageTypeID, "PackageTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PackageTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PackageTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceTypeID, "ServiceTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ServiceTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ServiceTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20317887/Views/ServicePackageFees/Index.cshtml
@model IEnumerable<SinExWebApp20317887.Models.ServicePackageFee>

@{
    ViewBag.Title = "Service Package Fees";
}

<h2>Service Package Fees</h2>
<hr />
<html>
<head>
    <style>
        table, td, th {
            border: 1px solid black;
        }

        th {
            text-align: center;
        }
    </style>
</head>
<body>

    @using (Html.BeginForm("Index", "ServicePackageFees", FormMethod.Get))
    {
        @Html.DropDownList("CurrencyCode",new SelectList (new[] { new {ID="CNY",Name="CNY" }, new { ID = "HKD", Name = "HKD" }, new { ID = "TWD", Name = "TWD" },
   new {ID="MOP",Name="MOP" },},"ID","Name",1))
        <input type="submit" value="Submit" />
    }



    <table class="table">
        <tr>
            <th rowspan="2">
                Service Type
            </th>
            <th colspan="5">
                Package Type
            </th>
        </tr>
        <tr>
            <th>Envelope</th>
            <th>Pak</th>
            <th>Tube</th>
            <th>Box</th>
            <th>Customer</th>
        </tr>

        @for (int i = 0; i <= 6; i++)
        {
            <tr>

                @foreach (var item in Model)
                {
                    if (item.ServiceTypeID == i)
                    {
                        if (item.PackageTypeID == 1)
                        {
                            <th>@Html.DisplayFor(modelItem => item.ServiceType.Type)</th>
                            <th>
                                @Html.DisplayFor(modelItem => item.Fee)
                            </th>
                        }
                        else if (item.PackageTypeID == 2)
                        {
                            <th colspan="2">
                                @Html.DisplayFor(modelItem => item.Fee)
                            </th>
                        }
                        else if (item.PackageTypeID == 4)
                        {
                            <th colspan="2">
                                @Html.DisplayFor(modelItem => item.Fee)
                            </th>
                        }


                    }

                }
            </tr>
            }

    </table>
</body>
</html>