SinExWebApp20317887/Models/Shipment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SinExWebApp20317887.Models
{
    [Table("Shipment")]
    public class Shipment
    {
        [Key]
        public virtual int WaybillId { get; set; }
        public virtual string ReferenceNumber { get; set; }
        public virtual string ServiceType { get; set; }
        public virtual DateTime ShippedDate { get; set; }
        public virtual DateTime DeliveredDate { get; set; }
        public virtual string RecipientName { get; set; }
        public virtual int NumberOfPackages { get; set; }
        public virtual string Origin { get; set; }
        public virtual string Destination { get; set; }
        public virtual string Status { get; set; }
        public virtual int ShippingAccountId { get; set; }

        //navigation property
        public virtual ShippingAccount ShippingAccount { get; set; }
    }
}

SinExWebApp20317887/Controllers/ShipmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SinExWebApp20317887.Models;
using SinExWebApp20317887.ViewModels;
using X.PagedList;

namespace SinExWebApp20317887.Controllers
{
    public class ShipmentsController : Controller
    {
        private SinExDatabaseContext db = new SinExDatabaseContext();

        // GET: Shipments/GenerateHistoryReport
        public ActionResult GenerateHistoryReport(int? ShippingAccountId,
            string Shipdaybefore,
        string Shipmonthbefore,
        string Shipyearbefore,
        string Shipdayafter,
        string Shipmonthafter,
        string Shipyearafter,

            string sortOrder, int? currentShippingAccountId, int? page, string currentShipdaybefore,
        string currentShipmonthbefore,
        string currentShipyearbefore,
        string currentShipdayafter,
        string currentShipmonthafter,
        string currentShipyearafter
)
        {
            // Instantiate an instance of the ShipmentsReportViewModel and the ShipmentsSearchViewModel.
            var shipmentSearch = new ShipmentsReportViewModel();
            shipmentSearch.Shipment = new ShipmentsSearchViewModel();

            //Code for paging
            ViewBag.CurrentSort = sortOrder;
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            if (ShippingAccountId == null)
            {
                ShippingAccountId = currentShippingAccountId;
            }
            else { page = 1; }
            if (Shipdaybefore == "" ||
        Shipmonthbefore == "" ||
        Shipyearbefore == "")
            {
                Shipdaybefore = currentShipdaybefore;
                Shipmonthbefore = currentShipmonthbefore;
                Shipyearbefore = currentShipyearbefore;
            }
            if (Shipdayafter == "" ||
Shipmonthafter == "" ||
Shipyearafter == "")
            {
                Shipdayafter = currentShipdayafter;
                Shipmonthafter = currentShipmonthafter;
                Shipyearafter = currentShipyearafter;
            }
           

            ViewBag.CurrentShippingAccountId = ShippingAccountId;
            ViewBag.CurrentShipdaybefore = Shipdaybefore;
            ViewBag.CurrentShipmonthbefore = Shipmonthbefore;
            ViewBag.CurrentShipyearbefore = Shipyearbefore;
            ViewBag.CurrentShipdayafter = Shipdayafter;
            ViewBag.CurrentShipmonthafter = Shipmonthafter;
            ViewBag.CurrentShipyearafter = Shipyearafter;

            // Populate the ShippingAccountId dropdown list.
            shipmentSearch.Shipment.ShippingAccounts = PopulateShippingAccountsDropdownList().ToList();
            shipmentSearch.Shipment.days = PopulateNumberDropdownList(1, 31).ToList();
            shipmentSearch.Shipment.months = PopulateNumberDropdownList(1, 12).ToList();
            DateTime now = DateTime.Now;
            shipmentSearch.Shipment.years = PopulateNumberDropdownList(now.Year - 2, now.Year + 5).ToList();
            ViewBag.ShippingAccountId = currentShippingAccountId;
            ViewBag.Shipdaybefore = currentShipdaybefore;
            ViewBag.Shipmonthbefore = currentShipmonthbefore;
            ViewBag.Shipyearbefore = currentShipyearbefore;
            ViewBag.Shipdayafter = currentShipdayafter;
            ViewBag.Shipmonthafter = currentShipmonthafter;
            ViewBag.Shipyearafter = currentShipyearafter;

            // shipmentSearch.Shipment.ShippingAccountId =(int) currentShippingAccountId;
            // Initialize the query to retrieve shipments using the ShipmentsListViewModel.
            var shipmentQuery = from s in db.Shipments
                                select new ShipmentsListViewModel
                                {
                                    WaybillId = s.WaybillId,
                                    ServiceType = s.ServiceType,
                                    ShippedDate = s.ShippedDate,
                                    DeliveredDate = s.DeliveredDate,
                                    RecipientName = s.RecipientName,
                                    NumberOfPackages = s.NumberOfPackages,
                                    Origin = s.Origin,
                                    Destination = s.Destination,
                                    ShippingAccountId = s.ShippingAccountId
                                };
            // Add the condition to select a spefic shipping account if shipping account id is not null.
            if (ShippingAccountId != null)
            {
                DateTime Shipbefore;
                DateTime Shipafter;
                DateTime Deliverybefore;
                DateTime Deliveryafter;
                int yeart, montht, dayt;
                // if (ShippedDateF != null) { shipmentQuery = shipmentQuery.Where(s => s.ShippedDate >= ShippedDateF); }
                if (((Shipdaybefore != "" && Shipmonthbefore != "" && Shipyearbefore != "")) && Shipdaybefore != null && Shipmonthbefore != null && Shipyearbefore != null)
                {
                    yeart = int.Parse(Shipyearbefore);
                    montht = int.Parse(Shipmonthbefore);
                    dayt = int.Parse(Shipdaybefore);
                    Shipbefore = new DateTime(yeart, montht, dayt);

                }
                else { Shipbefore = DateTime.MaxValue; }
                if (((Shipdayafter != "" && Shipmonthafter != "" && Shipyearafter != "")) && Shipdayafter != null && Shipmonthafter != null && Shipyearafter != null)
                {
                    yeart = int.Parse(Shipyearafter);
                    montht = int.Parse(Shipmonthafter);
                    dayt = int.Parse(Shipdayafter);

                    Shipafter = new DateTime(yeart, montht, dayt);

                }
                else { Shipafter = DateTime.MinValue; }


                // TODO: Construct the LINQ query to retrive only the shipments for the specified shipping account id.
                shipmentQuery = shipmentQuery.Where(s => s.ShippingAccountId == ShippingAccountId);

                shipmentQuery = shipmentQuery.Where(s => s.ShippedDate <= Shipbefore);
                shipmentQuery = shipmentQuery.Where(s => s.ShippedDate >= Shipafter);



                ViewBag.ServiceTypeSortParm = sortOrder == "serviceType" ? "serviceType_desc" : "serviceType";
                ViewBag.ShippedDateSortParm = sortOrder == "shippedDate" ? "shippedDate_desc" : "shippedDate";
                ViewBag.DeliveredDateSortParm = sortOrder == "deliveredDate" ? "deliveredDate_desc" : "deliveredDate";
                ViewBag.RecipientNameSortParm = sortOrder == "recipientName" ? "recipientName_desc" : "recipientName";
                ViewBag.OriginSortParm = sortOrder == "origin" ? "origin_desc" : "origin";
                ViewBag.DestinationSortParm = sortOrder == "destination" ? "destination_desc" : "destination";

                switch (sortOrder)
                {
                    case "serviceType":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.ServiceType); break;
                    case "serviceType_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.ServiceType); break;

                    case "shippedDate":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.ShippedDate); break;
                    case "shippedDate_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.ShippedDate); break;

                    case "deliveredDate":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.DeliveredDate); break;
                    case "deliveredDate_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.DeliveredDate); break;

                    case "recipientName":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.RecipientName); break;
                    case "recipientName_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.RecipientName); break;

                    case "origin":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.Origin); break;
                    case "origin_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.Origin); break;

                    case "destination":
                        shipmentQuery = shipmentQuery.OrderBy(s => s.Destination); break;
                    case "destination_desc":
                        shipmentQuery = shipmentQuery.OrderByDescending(s => s.Destination); break;

                    default: shipmentQuery = shipmentQuery.OrderBy(s => s.WaybillId); break;
                }
                shipmentSearch.Shipments = shipmentQuery.ToPagedList(pageNumber, pageSize);
            }
            else
            {
                // Return an empty result if no shipping account id has been selected.
                shipmentSearch.Shipments = new ShipmentsListViewModel[0].ToPagedList(pageNumber, pageSize);
            }



            return View(shipmentSearch);
        }

        private SelectList PopulateShippingAccountsDropdownList()
        {
            // TODO: Construct the LINQ query to retrieve the unique list of shipping account ids.
            var shippingAccountQuery = db.Shipments.Select(s => s.ShippingAccountId).Distinct().OrderBy(c => c);
            return new SelectList(shippingAccountQuery);
        }
        private SelectList PopulateNumberDropdownList(int s, int e)
        {
            // TODO: Construct the LINQ query to retrieve the unique list of shipping account ids.
            string[] arr = new string[e - s + 1];
            for (int i = 0; s <= e; s++, i++)
            {
                arr[i] = s.ToString();
            }
            return new SelectList(arr);
        }

SinExWebApp20317887/Views/Shipments/Create.cshtml
@model SinExWebApp20317887.Models.Shipment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shipment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ReferenceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReferenceNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReferenceNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveredDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecipientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecipientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecipientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPackages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPackages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPackages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippingAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippingAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20317887/Views/Shipments/Delete.cshtml
@model SinExWebApp20317887.Models.Shipment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecipientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPackages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfPackages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippingAccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippingAccountId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SinExWebApp20317887/Views/Shipments/Details.cshtml
@model SinExWebApp20317887.Models.Shipment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Shipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReferenceNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReferenceNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecipientName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecipientName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfPackages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfPackages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Origin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Origin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Destination)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Destination)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShippingAccountId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShippingAccountId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.WaybillId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SinExWebApp20317887/Views/Shipments/Edit.cshtml
@model SinExWebApp20317887.Models.Shipment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Shipment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.WaybillId)

        <div class="form-group">
            @Html.LabelFor(model => model.ReferenceNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReferenceNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReferenceNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveredDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveredDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveredDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecipientName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecipientName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecipientName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPackages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPackages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPackages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Origin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Origin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Origin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Destination, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Destination, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Destination, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShippingAccountId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShippingAccountId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShippingAccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SinExWebApp20317887/Views/Shipments/GenerateHistoryReport.cshtml
@model SinExWebApp20317887.ViewModels.ShipmentsReportViewModel

@{
    ViewBag.Title = "Shipment History";
 }

<h2>Shipment History</h2>

@Html.Partial("_ShipmentsSearchPartial",Model.Shipment)
@Html.Partial("_ShipmentsListPartial",Model.Shipments)
@Html.Partial("_ShipmentsPagingPartial",Model.Shipments)

SinExWebApp20317887/Views/Shipments/_ShipmentsPagingPartial.cshtml
@model X.PagedList.IPagedList<SinExWebApp20317887.ViewModels.ShipmentsListViewModel>
    @using X.PagedList.Mvc

@if (Model.PageCount > 1)
{
    <div class="pager">
        @Html.PagedListPager(Model, page => Url.Action("GenerateHistoryReport",new
   {page,
       sortOrder = ViewBag.DestinationSortParm,
       currentShippingAccountId = ViewBag.CurrentShippingAccountId,
       currentShipdaybefore = ViewBag.CurrentShipdaybefore,
       currentShipmonthbefore = ViewBag.CurrentShipmonthbefore,
       currentShipyearbefore = ViewBag.CurrentShipyearbefore,
       currentShipdayafter = ViewBag.CurrentShipdayafter,
       currentShipmonthafter = ViewBag.CurrentShipmonthafter,
       currentShipyearafter = ViewBag.CurrentShipyearafter,

   }))
        Page @Model.PageNumber of @Model.PageCount
    </div>
}

SinExWebApp20317887/Views/Shipments/_ShipmentsSearchPartial.cshtml
@model SinExWebApp20317887.ViewModels.ShipmentsSearchViewModel

@using (Html.BeginForm("GenerateHistoryReport", "Shipments", FormMethod.Get))
{
    @Html.LabelFor(a => a.ShippingAccountId, "Shipping Account: ")
    @Html.DropDownListFor(a => a.ShippingAccountId, Model.ShippingAccounts, "Please select",htmlAttributes:new {@Value=ViewBag.CurrentShippingAccount as int? })
    <input type="submit" value="Search" />
    <p></p>
    @Html.LabelFor(a => a.Shipyearafter, "ShippedDate After:")
    @Html.DropDownListFor(a => a.Shipyearafter, Model.years , "Year", htmlAttributes: new { @Value = ViewBag.CurrentShipyearafter as string })
    
    @Html.LabelFor(a => a.Shipmonthafter,"")
    @Html.DropDownListFor(a => a.Shipmonthafter, Model.months, "Month", htmlAttributes: new { @Value = ViewBag.CurrentShipmonthafter as string })
    
    @Html.LabelFor(a => a.Shipdayafter, "")
    @Html.DropDownListFor(a => a.Shipdayafter, Model.days, "Day", htmlAttributes: new { @Value = ViewBag.CurrentShipdayafter as string })
    <input type="submit" value="Search" />
    <p></p>
    @Html.LabelFor(a => a.Shipyearbefore, "ShippedDate Before:")
    @Html.DropDownListFor(a => a.Shipyearbefore, Model.years, "Year", htmlAttributes: new { @Value = ViewBag.CurrentShipyearbefore as string })
    
    @Html.LabelFor(a => a.Shipmonthbefore, "")
    @Html.DropDownListFor(a => a.Shipmonthbefore, Model.months, "Month", htmlAttributes: new { @Value = ViewBag.CurrentShipmonthbefore as string })
    
    @Html.LabelFor(a => a.Shipdaybefore, "")
    @Html.DropDownListFor(a => a.Shipdaybefore, Model.days, "Day", htmlAttributes: new { @Value = ViewBag.CurrentShipdaybefore as string })
    <input type="submit" value="Search" />
    <p></p>

}